/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReportRegistry {
  export type ReportRecordStruct = {
    reportId: string;
    issuer: AddressLike;
    epoch: BigNumberish;
    reportHash: BytesLike;
    attestationHash: BytesLike;
    ipfsCid: string;
    discrepancyBps: BigNumberish;
    anomalyFlagged: boolean;
    timestamp: BigNumberish;
    submitter: AddressLike;
  };

  export type ReportRecordStructOutput = [
    reportId: string,
    issuer: string,
    epoch: bigint,
    reportHash: string,
    attestationHash: string,
    ipfsCid: string,
    discrepancyBps: bigint,
    anomalyFlagged: boolean,
    timestamp: bigint,
    submitter: string
  ] & {
    reportId: string;
    issuer: string;
    epoch: bigint;
    reportHash: string;
    attestationHash: string;
    ipfsCid: string;
    discrepancyBps: bigint;
    anomalyFlagged: boolean;
    timestamp: bigint;
    submitter: string;
  };
}

export interface ReportRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeSubmitter"
      | "authorizedSubmitters"
      | "getIssuerReports"
      | "getLatestReport"
      | "getReport"
      | "issuerReports"
      | "owner"
      | "publishReport"
      | "regulatorAddress"
      | "renounceOwnership"
      | "reportCount"
      | "reports"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnomalyFlagged"
      | "OwnershipTransferred"
      | "ReportPublished"
      | "SubmitterAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeSubmitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedSubmitters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerReports",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestReport",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getReport", values: [string]): string;
  encodeFunctionData(
    functionFragment: "issuerReports",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publishReport",
    values: [ReportRegistry.ReportRecordStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "regulatorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reports", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeSubmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedSubmitters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReport", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuerReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regulatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AnomalyFlaggedEvent {
  export type InputTuple = [
    reportId: string,
    issuer: AddressLike,
    discrepancyBps: BigNumberish
  ];
  export type OutputTuple = [
    reportId: string,
    issuer: string,
    discrepancyBps: bigint
  ];
  export interface OutputObject {
    reportId: string;
    issuer: string;
    discrepancyBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportPublishedEvent {
  export type InputTuple = [
    reportId: string,
    issuer: AddressLike,
    epoch: BigNumberish,
    reportHash: BytesLike,
    anomalyFlagged: boolean
  ];
  export type OutputTuple = [
    reportId: string,
    issuer: string,
    epoch: bigint,
    reportHash: string,
    anomalyFlagged: boolean
  ];
  export interface OutputObject {
    reportId: string;
    issuer: string;
    epoch: bigint;
    reportHash: string;
    anomalyFlagged: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmitterAuthorizedEvent {
  export type InputTuple = [submitter: AddressLike];
  export type OutputTuple = [submitter: string];
  export interface OutputObject {
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReportRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReportRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReportRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeSubmitter: TypedContractMethod<
    [submitter: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedSubmitters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getIssuerReports: TypedContractMethod<
    [issuer: AddressLike],
    [string[]],
    "view"
  >;

  getLatestReport: TypedContractMethod<
    [issuer: AddressLike],
    [ReportRegistry.ReportRecordStructOutput],
    "view"
  >;

  getReport: TypedContractMethod<
    [reportId: string],
    [ReportRegistry.ReportRecordStructOutput],
    "view"
  >;

  issuerReports: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  publishReport: TypedContractMethod<
    [record: ReportRegistry.ReportRecordStruct],
    [void],
    "nonpayable"
  >;

  regulatorAddress: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportCount: TypedContractMethod<[], [bigint], "view">;

  reports: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        reportId: string;
        issuer: string;
        epoch: bigint;
        reportHash: string;
        attestationHash: string;
        ipfsCid: string;
        discrepancyBps: bigint;
        anomalyFlagged: boolean;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeSubmitter"
  ): TypedContractMethod<[submitter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedSubmitters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getIssuerReports"
  ): TypedContractMethod<[issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLatestReport"
  ): TypedContractMethod<
    [issuer: AddressLike],
    [ReportRegistry.ReportRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReport"
  ): TypedContractMethod<
    [reportId: string],
    [ReportRegistry.ReportRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "issuerReports"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishReport"
  ): TypedContractMethod<
    [record: ReportRegistry.ReportRecordStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "regulatorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        reportId: string;
        issuer: string;
        epoch: bigint;
        reportHash: string;
        attestationHash: string;
        ipfsCid: string;
        discrepancyBps: bigint;
        anomalyFlagged: boolean;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AnomalyFlagged"
  ): TypedContractEvent<
    AnomalyFlaggedEvent.InputTuple,
    AnomalyFlaggedEvent.OutputTuple,
    AnomalyFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReportPublished"
  ): TypedContractEvent<
    ReportPublishedEvent.InputTuple,
    ReportPublishedEvent.OutputTuple,
    ReportPublishedEvent.OutputObject
  >;
  getEvent(
    key: "SubmitterAuthorized"
  ): TypedContractEvent<
    SubmitterAuthorizedEvent.InputTuple,
    SubmitterAuthorizedEvent.OutputTuple,
    SubmitterAuthorizedEvent.OutputObject
  >;

  filters: {
    "AnomalyFlagged(string,address,uint256)": TypedContractEvent<
      AnomalyFlaggedEvent.InputTuple,
      AnomalyFlaggedEvent.OutputTuple,
      AnomalyFlaggedEvent.OutputObject
    >;
    AnomalyFlagged: TypedContractEvent<
      AnomalyFlaggedEvent.InputTuple,
      AnomalyFlaggedEvent.OutputTuple,
      AnomalyFlaggedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReportPublished(string,address,uint256,bytes32,bool)": TypedContractEvent<
      ReportPublishedEvent.InputTuple,
      ReportPublishedEvent.OutputTuple,
      ReportPublishedEvent.OutputObject
    >;
    ReportPublished: TypedContractEvent<
      ReportPublishedEvent.InputTuple,
      ReportPublishedEvent.OutputTuple,
      ReportPublishedEvent.OutputObject
    >;

    "SubmitterAuthorized(address)": TypedContractEvent<
      SubmitterAuthorizedEvent.InputTuple,
      SubmitterAuthorizedEvent.OutputTuple,
      SubmitterAuthorizedEvent.OutputObject
    >;
    SubmitterAuthorized: TypedContractEvent<
      SubmitterAuthorizedEvent.InputTuple,
      SubmitterAuthorizedEvent.OutputTuple,
      SubmitterAuthorizedEvent.OutputObject
    >;
  };
}
